services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rcs_app:latest
    container_name: rcs_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - rcs-network
    depends_on:
      - db
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: rcs_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "9091:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - rcs-network
    depends_on:
      - db

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: rcs_db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: rcs_app_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: Letmein@2025
      MYSQL_USER: rcs_user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rcs-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rcs_phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - "9092:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - rcs-network

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: rcs_redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - rcs-network

  # Websocket Service
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    image: rcs_websocket:latest
    container_name: rcs_websocket
    restart: unless-stopped
    tty: true
    ports:
      - "6001:6001"
    environment:
      SERVICE_NAME: websocket
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - rcs-network
    depends_on:
      - redis

  # Scheduler Service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: rcs_scheduler:latest
    container_name: rcs_scheduler
    restart: always
    working_dir: /var/www
    command: >
      sh -c "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
    volumes:
      - .:/var/www
    depends_on:
      - app
      - redis
    networks:
      - rcs-network

# Docker Networks
networks:
  rcs-network:
    driver: bridge

# Docker Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
